### ISSUE TITLE
Hosted examples are broken

### ISSUE THREAD

**Issue by rolo** [facebook/fixed-data-table#131]
Hiya. It appears that the hosted examples at https://facebook.github.io/fixed-data-table/ are broken.

https://facebook.github.io/fixed-data-table/example-object-data.html, and each of the 4 top level example links, give me `Uncaught TypeError: undefined is not a function` at `TouchExampleWrapper.js:44.`

Have tested on latest Chrome (42.0.2311.135) and Firefox (37.0.2) on Ubuntu 15.04 x64.

Figured it was worth pointing out incase you weren't aware.

Thanks :)

**Comment by pieterv** [comment]
Hmm interesting its working for me on Chrome and Firefox on Mac, it looks like Zynga scroller is failing for you. Do you mind checking to see if your getting any failed network requests?

**Comment by rolo** [comment]
No probs. Doesn't look like any failed network requests. Screenshot from 

![data-table-network-requests](https://cloud.githubusercontent.com/assets/28436/7481018/ef4558a2-f364-11e4-96ae-e8d3c2e5e823.png)

Have done it in incognito mode so no extensions (I removed adblock after noticing it was in this screenshot).

Let me know if I can provide anything more to help, or if this is definitely just my end I'll go away :)

**Comment by rolo** [comment]
Tried on my wife's windows machine and seeing the same thing. Here's a Firefox console screenshot incase that's any help.

![fixed-data-table-firefox-console](https://cloud.githubusercontent.com/assets/28436/7481308/0288d66c-f367-11e4-9fbe-ce3e6e4b3a7f.png)

**Comment by pieterv** [comment]
Hmmm thats interesting i will have to take a deeper look, thanks for the detailed info!

**Comment by jonashagstedt** [comment]
I can confirm that they are not working on Chrome (OSX) 42.0.2311.135 (64-bit)

**Comment by harel** [comment]
Can confirm also broken on 
Chrome (Ubuntu) 41.0.2272.118 (64-bit)  and 42.0.2311.135 (64-bit).  
Firefox (Ubuntu) 37.0.1

**Comment by jonashagstedt** [comment]
I looked at the source and it's referencing "https://cdn.rawgit.com/zynga/scroller/master/src/Scroller.js".
That file doesn't seem to contain anything.

**Comment by pieterv** [comment]
Hmm looks like this is a CDN issue, i will see if i can find a more reliable place to host this file.
